### ISSUE TITLE
日历打开图标显示有问题

### ISSUE THREAD

**Issue by ACodingJie** [xkloveme/utools-calendar#5]
![](https://files.catbox.moe/smcz2j.png)

**Comment by ACodingJie** [comment]
电脑重启之后就可以了 ... 电脑晚上一般都是睡眠

**Comment by ACodingJie** [comment]
顺带提个小需求, 期望日历日期可以上下滚动, 不只是月份点击的跳转

**Comment by ACodingJie** [comment]
![](https://cdn.jsdelivr.net/gh/ACodingJie/picture/image/1602469612408-1602469612407.png)


应该是 win10 系统睡眠之后 再次打开产生的问题 上次是29号睡眠的

**Comment by jianhao** [comment]
俺也一样，这不修复下么，老板

**Comment by xkloveme** [comment]
已修复感谢提醒
